// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class InteractingwithchatsandclicksonrandommenusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void interactingwithchatsandclicksonrandommenus() {
    driver.get("https://staging.vouch.sg/api/v1/merchants/bot/5c0899a0f82bb561b4eff079undefined");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("vc-widget-title")));
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 50);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("vc-input")));
    }
    driver.findElement(By.id("vc-input")).sendKeys("Good morning!");
    driver.findElement(By.cssSelector(".vciw-play3")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".quick-reply")));
    }
    driver.findElement(By.id("vc-input")).sendKeys("Reservations");
    driver.findElement(By.cssSelector(".vciw-play3")).click();
    assertThat(driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(1) > .quick-reply")).getText(), is("Room Reservations"));
    driver.findElement(By.id("vc-input")).sendKeys("Room Reservations");
    driver.findElement(By.cssSelector(".vciw-play3")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(3) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(3) > .quick-reply")).click();
    assertThat(driver.findElement(By.cssSelector(".quick-reply")).getText(), is("Main Menu"));
    driver.findElement(By.cssSelector(".quick-reply")).click();
    driver.findElement(By.xpath("(//div[@id=\'vcw-card-button\'])[33]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".quick-reply")));
    }
    driver.findElement(By.cssSelector(".quick-reply")).click();
    driver.findElement(By.xpath("(//div[@id=\'vcw-card-button\'])[39]")).click();
    driver.findElement(By.cssSelector("#vc-message-no-5d330cb496f82c31953ebb00 .vcw-card:nth-child(4) #vcw-card-button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(1) > .quick-reply")));
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".quick-reply")));
    }
    driver.findElement(By.cssSelector(".quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.elementToBeClickable(By.id("vc-input")));
    }
    driver.findElement(By.id("vc-input")).sendKeys("Reservations");
    driver.findElement(By.cssSelector(".vciw-play3")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-card:nth-child(8) #vcw-card-button")));
    }
    driver.findElement(By.cssSelector(".vcw-card:nth-child(8) #vcw-card-button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(3) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(3) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(5) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(5) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(6) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(6) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 200);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(2) > .quick-reply")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".vcw-gallery-item-simple:nth-child(4) > .quick-reply")));
    }
    driver.findElement(By.cssSelector(".vcw-gallery-item-simple:nth-child(4) > .quick-reply")).click();
    driver.close();
  }
}
